import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Authentication using Next.js & Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container text-center my-3">
          <h1>Welcome to my Website</h1>
          <p>You can Login and Sign up for Free ! Thank you ❤</p>
        </div>
      </main>
    </>
  )
}
